CREATE TABLE [dbo].[TRANSPORTATION_TOPOLOGY_POINT]
(
[OID] [int] NOT NULL,
[OriginObjectClassName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OriginObjectID] [int] NULL,
[DestinationObjectClassName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DestinationObjectID] [int] NULL,
[RuleType] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RuleDescription] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[isException] [int] NOT NULL,
[Shape] [sys].[geometry] NULL,
[GDB_GEOMATTR_DATA] [varbinary] (max) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TRANSPORTATION_TOPOLOGY_POINT] ADD CONSTRAINT [g7_ck] CHECK (([SHAPE].[STSrid]=(2285)))
GO
ALTER TABLE [dbo].[TRANSPORTATION_TOPOLOGY_POINT] ADD CONSTRAINT [R36_pk] PRIMARY KEY CLUSTERED ([OID]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
CREATE SPATIAL INDEX [S7_idx] ON [dbo].[TRANSPORTATION_TOPOLOGY_POINT] ([Shape]) USING geometry_auto_grid  WITH (BOUNDING_BOX = (1174210.6470588236, -82858.8235294117, 1452648.6470588236, 460142.8823529412), CELLS_PER_OBJECT = 16) ON [PRIMARY]
GO
