CREATE TABLE [dbo].[TRANSREFEDGES]
(
[OBJECTID] [int] NOT NULL,
[Enabled] [smallint] NULL,
[PSRCEdgeID] [int] NOT NULL,
[FTRsegID] [int] NULL,
[FacilityType] [int] NOT NULL,
[NewFacilityType] [int] NULL,
[INode] [int] NOT NULL,
[JNode] [int] NOT NULL,
[InServiceDate] [smallint] NOT NULL,
[OutServiceDate] [smallint] NOT NULL,
[dateLastUpdated] [datetime2] NOT NULL,
[ActiveLink] [smallint] NOT NULL,
[LinkType] [smallint] NULL,
[FunctionalClass] [int] NOT NULL,
[Modes] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MTS] [int] NOT NULL,
[CMSlinkID] [int] NULL,
[CMScriticalLinkID] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Oneway] [int] NOT NULL,
[Fullname] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [datetime2] NULL,
[LastEditor] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EditNotes] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Tonnage] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GlobalEID] [int] NULL,
[Processing] [int] NULL,
[CountID] [int] NULL,
[CountyID] [smallint] NULL,
[StateRoute] [int] NULL,
[OldPSRCEdgeID] [int] NULL,
[OSMID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OSMNetID] [int] NULL,
[highway] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OSM_Oneway] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CorridorID] [int] NULL,
[RegShared] [smallint] NULL,
[FGTS] [smallint] NULL,
[Source] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Shape] [sys].[geometry] NULL,
[GDB_GEOMATTR_DATA] [varbinary] (max) NULL,
[GlobalID] [uniqueidentifier] NOT NULL CONSTRAINT [DF__TRANSREFE__Globa__2F4FF79D] DEFAULT ('{00000000-0000-0000-0000-000000000000}'),
[PSRCEdgeID_1] [int] NULL,
[IJLanesGPAM] [int] NULL,
[IJLanesGPMD] [int] NULL,
[IJLanesGPPM] [int] NULL,
[IJLanesGPEV] [int] NULL,
[IJLanesGPNI] [int] NULL,
[JILanesGPAM] [int] NULL,
[JILanesGPMD] [int] NULL,
[JILanesGPPM] [int] NULL,
[JILanesGPEV] [int] NULL,
[JILanesGPNI] [int] NULL,
[IJlanesGPadjust] [numeric] (6, 2) NULL,
[JIlanesGPadjust] [numeric] (6, 2) NULL,
[IJLanesHOVAM] [int] NULL,
[IJLanesHOVMD] [int] NULL,
[IJLanesHOVPM] [int] NULL,
[IJLanesHOVEV] [int] NULL,
[IJLanesHOVNI] [int] NULL,
[JILanesHOVAM] [int] NULL,
[JILanesHOVMD] [int] NULL,
[JILanesHOVPM] [int] NULL,
[JILanesHOVEV] [int] NULL,
[JILanesHOVNI] [int] NULL,
[IJSpeedLimit] [int] NULL,
[JISpeedLimit] [int] NULL,
[IJVDFunc] [int] NULL,
[JIVDFunc] [int] NULL,
[IJLaneCapGP] [int] NULL,
[IJLaneCapHOV] [int] NULL,
[JILaneCapGP] [int] NULL,
[JILaneCapHOV] [int] NULL,
[IJSideWalks] [int] NULL,
[JISideWalks] [int] NULL,
[IJBikeLanes] [int] NULL,
[JIBikeLanes] [int] NULL,
[IJLanesTR] [int] NULL,
[JILanesTR] [int] NULL,
[IJLanesTK] [int] NULL,
[JILanesTK] [int] NULL,
[PSRCE2_ID] [int] NULL,
[dateLastUpdated_1] [datetime2] NULL,
[DateCreated_1] [datetime2] NULL,
[LastEditor_1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DataSource] [smallint] NULL,
[Processing_1] [int] NULL,
[BikeSigns] [int] NULL,
[SidewalkSource] [smallint] NULL,
[BikeEditorNotes] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IJBikeFacility] [int] NULL,
[JIBikeFacility] [int] NULL,
[IJPedFacilities] [int] NULL,
[JIPedFacilities] [int] NULL,
[IJBikeType] [int] NULL,
[JIBikeType] [int] NULL,
[IJBikeFacilities] [int] NULL,
[JIBikeFacilities] [int] NULL,
[IJCorridorID] [int] NULL,
[JICorridorID] [int] NULL,
[Channelization] [numeric] (38, 8) NULL,
[BikeSource_hold] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BikeSource] [smallint] NULL,
[PedBikeNotes] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[created_user] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[created_date] [datetime2] NULL,
[last_edited_user] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[last_edited_date] [datetime2] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TRANSREFEDGES] ADD CONSTRAINT [g15_ck] CHECK (([SHAPE].[STSrid]=(2285)))
GO
ALTER TABLE [dbo].[TRANSREFEDGES] ADD CONSTRAINT [R44_pk] PRIMARY KEY CLUSTERED ([OBJECTID]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [UUID_44] ON [dbo].[TRANSREFEDGES] ([GlobalID]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [UUID_OID_44] ON [dbo].[TRANSREFEDGES] ([GlobalID], [OBJECTID]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [G116PSRCEdgeID] ON [dbo].[TRANSREFEDGES] ([PSRCEdgeID]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
CREATE SPATIAL INDEX [S15_idx] ON [dbo].[TRANSREFEDGES] ([Shape]) USING geometry_auto_grid  WITH (BOUNDING_BOX = (1057775.588235294, -176376.9411764706, 1846505.294117647, 564501.29411764711), CELLS_PER_OBJECT = 16) ON [PRIMARY]
GO
