CREATE TABLE [dbo].[D52]
(
[SDE_STATE_ID] [bigint] NOT NULL,
[SDE_DELETES_ROW_ID] [int] NOT NULL,
[DELETED_AT] [bigint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[D52] ADD CONSTRAINT [d52_pk] PRIMARY KEY NONCLUSTERED ([SDE_STATE_ID], [SDE_DELETES_ROW_ID], [DELETED_AT]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
CREATE CLUSTERED INDEX [d52_idx2] ON [dbo].[D52] ([DELETED_AT]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
