CREATE TABLE [dbo].[D49]
(
[SDE_STATE_ID] [bigint] NOT NULL,
[SDE_DELETES_ROW_ID] [int] NOT NULL,
[DELETED_AT] [bigint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[D49] ADD CONSTRAINT [d49_pk] PRIMARY KEY NONCLUSTERED ([SDE_STATE_ID], [SDE_DELETES_ROW_ID], [DELETED_AT]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
CREATE CLUSTERED INDEX [d49_idx2] ON [dbo].[D49] ([DELETED_AT]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
