CREATE TABLE [dbo].[GDB_ITEMTYPES]
(
[ObjectID] [int] NOT NULL,
[UUID] [uniqueidentifier] NOT NULL,
[Name] [nvarchar] (257) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ParentTypeID] [uniqueidentifier] NOT NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[GDB_ITEM_TYP_TR] ON [dbo].[GDB_ITEMTYPES] 
FOR INSERT, UPDATE, DELETE AS 
BEGIN 
SET NOCOUNT ON 
SET LOCK_TIMEOUT 0 
SET XACT_ABORT OFF 
DECLARE @ErrorMessage NVARCHAR(2048), 
@ErrorSeverity INT, 
@ErrorState INT; 
 BEGIN TRY 
UPDATE dbo.GDB_TABLES_LAST_MODIFIED SET last_modified_count = last_modified_count + 1 
WHERE table_name = 'GDB_ITEMTYPES' 
IF @@ROWCOUNT = 0 
BEGIN 
INSERT INTO dbo.GDB_TABLES_LAST_MODIFIED VALUES ('GDB_ITEMTYPES', 1) 
END 
END TRY 
BEGIN CATCH 
IF ERROR_NUMBER() != 1222 
BEGIN 
SELECT @ErrorMessage = ERROR_MESSAGE(), 
@ErrorSeverity = ERROR_SEVERITY(), 
@ErrorState = ERROR_STATE(); 
RAISERROR(@ErrorMessage, @ErrorSeverity, @ErrorState); 
END 
RETURN 
END CATCH 
END 

GO
CREATE NONCLUSTERED INDEX [ItemTypes_Name_idx] ON [dbo].[GDB_ITEMTYPES] ([Name]) WITH (FILLFACTOR=100, ALLOW_PAGE_LOCKS=OFF) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [R8_SDE_ROWID_UK] ON [dbo].[GDB_ITEMTYPES] ([ObjectID]) WITH (FILLFACTOR=100, ALLOW_PAGE_LOCKS=OFF) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [ItemTypes_ParentTypeID_idx] ON [dbo].[GDB_ITEMTYPES] ([ParentTypeID]) WITH (FILLFACTOR=100, ALLOW_PAGE_LOCKS=OFF) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [ItemTypes_UUID_idx] ON [dbo].[GDB_ITEMTYPES] ([UUID]) WITH (ALLOW_PAGE_LOCKS=OFF) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[GDB_ITEMTYPES] TO [public] WITH GRANT OPTION
GO
GRANT INSERT ON  [dbo].[GDB_ITEMTYPES] TO [public] WITH GRANT OPTION
GO
GRANT SELECT ON  [dbo].[GDB_ITEMTYPES] TO [public] WITH GRANT OPTION
GO
GRANT UPDATE ON  [dbo].[GDB_ITEMTYPES] TO [public] WITH GRANT OPTION
GO
ALTER TABLE [dbo].[GDB_ITEMTYPES] SET ( LOCK_ESCALATION = DISABLE )
GO
