CREATE TABLE [dbo].[MODETOLLS]
(
[OBJECTID] [int] NOT NULL,
[PSRCEdgeID] [int] NOT NULL,
[IJtollSOVAM] [int] NOT NULL,
[IJtollSOVMD] [int] NOT NULL,
[IJtollSOVPM] [int] NOT NULL,
[IJtollSOVEV] [int] NOT NULL,
[IJtollSOVNI] [int] NOT NULL,
[JItollSOVAM] [int] NOT NULL,
[JItollSOVMD] [int] NOT NULL,
[JItollSOVPM] [int] NOT NULL,
[JItollSOVEV] [int] NOT NULL,
[JItollSOVNI] [int] NOT NULL,
[IJtollHOV2AM] [int] NOT NULL,
[IJtollHOV2MD] [int] NOT NULL,
[IJtollHOV2PM] [int] NOT NULL,
[IJtollHOV2EV] [int] NOT NULL,
[IJtollHOV2NI] [int] NOT NULL,
[JItollHOV2AM] [int] NOT NULL,
[JItollHOV2MD] [int] NOT NULL,
[JItollHOV2PM] [int] NOT NULL,
[JItollHOV2EV] [int] NOT NULL,
[JItollHOV2NI] [int] NOT NULL,
[IJtollHOV3AM] [int] NOT NULL,
[IJtollHOV3MD] [int] NOT NULL,
[IJtollHOV3PM] [int] NOT NULL,
[IJtollHOV3EV] [int] NOT NULL,
[IJtollHOV3NI] [int] NOT NULL,
[JItollHOV3AM] [int] NOT NULL,
[JItollHOV3MD] [int] NOT NULL,
[JItollHOV3PM] [int] NOT NULL,
[JItollHOV3EV] [int] NOT NULL,
[JItollHOV3NI] [int] NOT NULL,
[IJtollTrkLtAM] [int] NOT NULL,
[IJtollTrkLtMD] [int] NOT NULL,
[IJtollTrkLtPM] [int] NOT NULL,
[IJtollTrkLtEV] [int] NOT NULL,
[IJtollTrkLtNI] [int] NOT NULL,
[JItollTrkLtAM] [int] NOT NULL,
[JItollTrkLtMD] [int] NOT NULL,
[JItollTrkLtPM] [int] NOT NULL,
[JItollTrkLtEV] [int] NOT NULL,
[JItollTrkLtNI] [int] NOT NULL,
[IJtollTrkMedAM] [int] NOT NULL,
[IJtollTrkMedMD] [int] NOT NULL,
[IJtollTrkMedPM] [int] NOT NULL,
[IJtollTrkMedEV] [int] NOT NULL,
[IJtollTrkMedNI] [int] NOT NULL,
[JItollTrkMedAM] [int] NOT NULL,
[JItollTrkMedMD] [int] NOT NULL,
[JItollTrkMedPM] [int] NOT NULL,
[JItollTrkMedEV] [int] NOT NULL,
[JItollTrkMedNI] [int] NOT NULL,
[IJtollTrkHvyAM] [int] NOT NULL,
[IJtollTrkHvyMD] [int] NOT NULL,
[IJtollTrkHvyPM] [int] NOT NULL,
[IJtollTrkHvyEV] [int] NOT NULL,
[IJtollTrkHvyNI] [int] NOT NULL,
[JItollTrkHvyAM] [int] NOT NULL,
[JItollTrkHvyMD] [int] NOT NULL,
[JItollTrkHvyPM] [int] NOT NULL,
[JItollTrkHvyEV] [int] NOT NULL,
[JItollTrkHvyNI] [int] NOT NULL,
[IJcostAddlAM] [int] NOT NULL,
[IJcostAddlMD] [int] NOT NULL,
[IJcostAddlPM] [int] NOT NULL,
[IJcostAddlEV] [int] NOT NULL,
[IJcostAddlNI] [int] NOT NULL,
[JIcostAddlAM] [int] NOT NULL,
[JIcostAddlMD] [int] NOT NULL,
[JIcostAddlPM] [int] NOT NULL,
[JIcostAddlEV] [int] NOT NULL,
[JIcostAddlNI] [int] NOT NULL,
[DateCreated] [datetime2] NULL,
[DateLastUpdated] [datetime2] NULL,
[LastEditor] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Processing] [int] NULL,
[InServiceDate] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [R15_SDE_ROWID_UK] ON [dbo].[MODETOLLS] ([OBJECTID]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [G85PSRCEdgeID] ON [dbo].[MODETOLLS] ([PSRCEdgeID]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
