CREATE TABLE [dbo].[TBLBIKECOUNTS]
(
[OBJECTID] [int] NOT NULL,
[Jurisdiction] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[County] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Agency] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FollowUpNotes] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PSRCEdgeID] [int] NULL,
[SegmentID] [int] NULL,
[CrossStreets] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Latitude] [numeric] (38, 8) NULL,
[Longitude] [numeric] (38, 8) NULL,
[Year] [int] NULL,
[CountDate] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[P_1] [int] NULL,
[P_2] [int] NULL,
[P_3] [int] NULL,
[P_4] [int] NULL,
[P_D] [int] NULL,
[B_1] [int] NULL,
[B_2] [int] NULL,
[B_3] [int] NULL,
[B_4] [int] NULL,
[B_D] [int] NULL,
[P_IJ_1] [int] NULL,
[P_IJ_2] [int] NULL,
[P_IJ_3] [int] NULL,
[P_IJ_4] [int] NULL,
[P_IJ_D] [int] NULL,
[B_IJ_1] [int] NULL,
[B_IJ_2] [int] NULL,
[B_IJ_3] [int] NULL,
[B_IJ_4] [int] NULL,
[B_IJ_D] [int] NULL,
[P_JI_1] [int] NULL,
[P_JI_2] [int] NULL,
[P_JI_3] [int] NULL,
[P_JI_4] [int] NULL,
[P_JI_D] [int] NULL,
[B_JI_1] [int] NULL,
[B_JI_2] [int] NULL,
[B_JI_3] [int] NULL,
[B_JI_4] [int] NULL,
[B_JI_D] [int] NULL,
[PSRCJunctID] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [R16_SDE_ROWID_UK] ON [dbo].[TBLBIKECOUNTS] ([OBJECTID]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
