CREATE TABLE [dbo].[TBLPROJECTSINSCENARIOS]
(
[OBJECTID] [int] NOT NULL,
[Scenario_ID] [int] NULL,
[projID] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[version] [int] NOT NULL,
[ScenarioName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[intProjID] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [R18_SDE_ROWID_UK] ON [dbo].[TBLPROJECTSINSCENARIOS] ([OBJECTID]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
