CREATE TABLE [dbo].[a29]
(
[OBJECTID] [int] NOT NULL,
[projRteID] [int] NULL,
[projDBS] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[projID] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[version] [int] NOT NULL,
[InServiceDate] [smallint] NOT NULL,
[OutServiceDate] [smallint] NULL,
[CompletionDate] [datetime2] NULL,
[Modes] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IJLanesGPAM] [int] NOT NULL,
[IJLanesGPMD] [int] NOT NULL,
[IJLanesGPPM] [int] NOT NULL,
[IJLanesGPEV] [int] NOT NULL,
[IJLanesGPNI] [int] NOT NULL,
[JILanesGPAM] [int] NOT NULL,
[JILanesGPMD] [int] NOT NULL,
[JILanesGPPM] [int] NOT NULL,
[JILanesGPEV] [int] NOT NULL,
[JILanesGPNI] [int] NOT NULL,
[IJlanesGPadjust] [numeric] (6, 2) NOT NULL,
[JIlanesGPadjust] [numeric] (6, 2) NOT NULL,
[IJLanesHOVAM] [int] NOT NULL,
[IJLanesHOVMD] [int] NOT NULL,
[IJLanesHOVPM] [int] NOT NULL,
[IJLanesHOVEV] [int] NOT NULL,
[IJLanesHOVNI] [int] NOT NULL,
[JILanesHOVAM] [int] NOT NULL,
[JILanesHOVMD] [int] NOT NULL,
[JILanesHOVPM] [int] NOT NULL,
[JILanesHOVEV] [int] NOT NULL,
[JILanesHOVNI] [int] NOT NULL,
[IJSpeedLimit] [int] NOT NULL,
[JISpeedLimit] [int] NOT NULL,
[IJVDFunc] [int] NOT NULL,
[JIVDFunc] [int] NOT NULL,
[IJLaneCapGP] [int] NOT NULL,
[IJLaneCapHOV] [int] NOT NULL,
[JILaneCapGP] [int] NOT NULL,
[JILaneCapHOV] [int] NOT NULL,
[IJSideWalks] [int] NOT NULL,
[JISideWalks] [int] NOT NULL,
[IJBikeLanes] [int] NOT NULL,
[JIBikeLanes] [int] NOT NULL,
[IJLanesTR] [int] NOT NULL,
[JILanesTR] [int] NOT NULL,
[IJLanesTK] [int] NOT NULL,
[JILanesTK] [int] NOT NULL,
[dateLastUpdated] [datetime2] NULL,
[DateCreated] [datetime2] NULL,
[LastEditor] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[EditNotes] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Processing] [int] NULL,
[IJBikeFacility] [int] NULL,
[JIBikeFacility] [int] NULL,
[IJBikeType] [int] NULL,
[JIBikeType] [int] NULL,
[SDE_STATE_ID] [bigint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[a29] ADD CONSTRAINT [a29_rowid_ix1] PRIMARY KEY NONCLUSTERED ([OBJECTID], [SDE_STATE_ID]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [G99projRteID_a] ON [dbo].[a29] ([projRteID]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [a29_state_ix2] ON [dbo].[a29] ([SDE_STATE_ID]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
