CREATE TABLE [dbo].[TRANSPORTATION_TOPOLOGY_LINE]
(
[OID] [int] NOT NULL,
[OriginObjectClassName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OriginObjectID] [int] NULL,
[DestinationObjectClassName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DestinationObjectID] [int] NULL,
[RuleType] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RuleDescription] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[isException] [int] NOT NULL,
[Shape] [sys].[geometry] NULL,
[GDB_GEOMATTR_DATA] [varbinary] (max) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TRANSPORTATION_TOPOLOGY_LINE] ADD CONSTRAINT [g9_ck] CHECK (([SHAPE].[STSrid]=(2285)))
GO
ALTER TABLE [dbo].[TRANSPORTATION_TOPOLOGY_LINE] ADD CONSTRAINT [R38_pk] PRIMARY KEY CLUSTERED ([OID]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
CREATE SPATIAL INDEX [S9_idx] ON [dbo].[TRANSPORTATION_TOPOLOGY_LINE] ([Shape]) USING geometry_auto_grid  WITH (BOUNDING_BOX = (1174210.6470588236, -83079.705882353, 1452648.6470588236, 468940.5294117647), CELLS_PER_OBJECT = 16) ON [PRIMARY]
GO
