CREATE TABLE [dbo].[GDB_EDITINGTEMPLATERELATIONSHIPS]
(
[objectid] [int] NOT NULL,
[type] [smallint] NOT NULL,
[originid] [uniqueidentifier] NOT NULL,
[destid] [uniqueidentifier] NOT NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [EdTemplateRlships_DestID_idx] ON [dbo].[GDB_EDITINGTEMPLATERELATIONSHIPS] ([destid]) WITH (FILLFACTOR=100, ALLOW_PAGE_LOCKS=OFF) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [R14_SDE_ROWID_UK] ON [dbo].[GDB_EDITINGTEMPLATERELATIONSHIPS] ([objectid]) WITH (FILLFACTOR=100, ALLOW_PAGE_LOCKS=OFF) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [EdTemplateRlships_OriginID_idx] ON [dbo].[GDB_EDITINGTEMPLATERELATIONSHIPS] ([originid]) WITH (FILLFACTOR=100, ALLOW_PAGE_LOCKS=OFF) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [EdTemplateRlships_Type_idx] ON [dbo].[GDB_EDITINGTEMPLATERELATIONSHIPS] ([type]) WITH (FILLFACTOR=100, ALLOW_PAGE_LOCKS=OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GDB_EDITINGTEMPLATERELATIONSHIPS] ADD CONSTRAINT [EdTemplateRlships_OriginID_fk] FOREIGN KEY ([originid]) REFERENCES [dbo].[GDB_EDITINGTEMPLATES] ([globalid])
GO
GRANT DELETE ON  [dbo].[GDB_EDITINGTEMPLATERELATIONSHIPS] TO [public] WITH GRANT OPTION
GO
GRANT INSERT ON  [dbo].[GDB_EDITINGTEMPLATERELATIONSHIPS] TO [public] WITH GRANT OPTION
GO
GRANT SELECT ON  [dbo].[GDB_EDITINGTEMPLATERELATIONSHIPS] TO [public] WITH GRANT OPTION
GO
GRANT UPDATE ON  [dbo].[GDB_EDITINGTEMPLATERELATIONSHIPS] TO [public] WITH GRANT OPTION
GO
ALTER TABLE [dbo].[GDB_EDITINGTEMPLATERELATIONSHIPS] SET ( LOCK_ESCALATION = DISABLE )
GO
