CREATE TABLE [dbo].[a26]
(
[OBJECTID] [int] NOT NULL,
[NRouteID] [int] NULL,
[MStart] [numeric] (8, 2) NOT NULL,
[MStop] [numeric] (8, 2) NOT NULL,
[SDE_STATE_ID] [bigint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[a26] ADD CONSTRAINT [a26_rowid_ix1] PRIMARY KEY NONCLUSTERED ([OBJECTID], [SDE_STATE_ID]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [G96NRouteID_a] ON [dbo].[a26] ([NRouteID]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [a26_state_ix2] ON [dbo].[a26] ([SDE_STATE_ID]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
