CREATE TABLE [dbo].[SDE_GEOMETRY1]
(
[GEOMETRY_ID] [int] NOT NULL,
[CAD] [varbinary] (max) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SDE_GEOMETRY1] ADD CONSTRAINT [geom1_idx] PRIMARY KEY CLUSTERED ([GEOMETRY_ID]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[SDE_GEOMETRY1] TO [public] WITH GRANT OPTION
GO
GRANT INSERT ON  [dbo].[SDE_GEOMETRY1] TO [public] WITH GRANT OPTION
GO
GRANT SELECT ON  [dbo].[SDE_GEOMETRY1] TO [public] WITH GRANT OPTION
GO
GRANT UPDATE ON  [dbo].[SDE_GEOMETRY1] TO [public] WITH GRANT OPTION
GO
