CREATE TABLE [dbo].[GDB_TABLES_LAST_MODIFIED]
(
[table_name] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[last_modified_count] [int] NOT NULL
) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [GDB_LMODIFIED_IX1] ON [dbo].[GDB_TABLES_LAST_MODIFIED] ([table_name]) WITH (ALLOW_PAGE_LOCKS=OFF) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[GDB_TABLES_LAST_MODIFIED] TO [public] WITH GRANT OPTION
GO
GRANT INSERT ON  [dbo].[GDB_TABLES_LAST_MODIFIED] TO [public] WITH GRANT OPTION
GO
GRANT SELECT ON  [dbo].[GDB_TABLES_LAST_MODIFIED] TO [public] WITH GRANT OPTION
GO
GRANT UPDATE ON  [dbo].[GDB_TABLES_LAST_MODIFIED] TO [public] WITH GRANT OPTION
GO
ALTER TABLE [dbo].[GDB_TABLES_LAST_MODIFIED] SET ( LOCK_ESCALATION = DISABLE )
GO
