CREATE TABLE [dbo].[GDB_ITEMS]
(
[ObjectID] [int] NOT NULL,
[UUID] [uniqueidentifier] NOT NULL,
[Type] [uniqueidentifier] NOT NULL,
[Name] [nvarchar] (257) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PhysicalName] [nvarchar] (257) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Path] [nvarchar] (770) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Url] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Properties] [int] NULL,
[Defaults] [varbinary] (max) NULL,
[DatasetSubtype1] [int] NULL,
[DatasetSubtype2] [int] NULL,
[DatasetInfo1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DatasetInfo2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ContingentValues] [varbinary] (max) NULL,
[Definition] [xml] NULL,
[Documentation] [xml] NULL,
[ItemInfo] [xml] NULL,
[Shape] [sys].[geometry] NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[GDB_ITEMS_TAB_TR] ON [dbo].[GDB_ITEMS] 
FOR INSERT, UPDATE, DELETE AS 
BEGIN 
SET NOCOUNT ON 
SET LOCK_TIMEOUT 0 
SET XACT_ABORT OFF 
DECLARE @ErrorMessage NVARCHAR(2048), 
@ErrorSeverity INT, 
@ErrorState INT; 
IF (SELECT COUNT(*) from inserted WHERE Type NOT IN ('4ED4A58E-621F-4043-95ED-850FBA45FCBC', 'D98421EB-D582-4713-9484-43304D0810F6','DC64B6E4-DC0F-43BD-B4F5-F22385DCF055','5B966567-FB87-4DDE-938B-B4B37423539D','D86502F9-9758-45C6-9D23-6DD1A0107B47')) > 0  OR 
(SELECT COUNT(*) from deleted WHERE Type NOT IN ('4ED4A58E-621F-4043-95ED-850FBA45FCBC', 'D98421EB-D582-4713-9484-43304D0810F6','DC64B6E4-DC0F-43BD-B4F5-F22385DCF055','5B966567-FB87-4DDE-938B-B4B37423539D','D86502F9-9758-45C6-9D23-6DD1A0107B47')) > 0 
 BEGIN 
 BEGIN TRY 
UPDATE dbo.GDB_TABLES_LAST_MODIFIED SET last_modified_count = last_modified_count + 1 
WHERE table_name = 'GDB_ITEMS' 
IF @@ROWCOUNT = 0 
BEGIN 
INSERT INTO dbo.GDB_TABLES_LAST_MODIFIED VALUES ('GDB_ITEMS', 1) 
END 
END TRY 
BEGIN CATCH 
IF ERROR_NUMBER() != 1222 
BEGIN 
SELECT @ErrorMessage = ERROR_MESSAGE(), 
@ErrorSeverity = ERROR_SEVERITY(), 
@ErrorState = ERROR_STATE(); 
RAISERROR(@ErrorMessage, @ErrorSeverity, @ErrorState); 
END 
RETURN 
END CATCH 
END 
END
GO
ALTER TABLE [dbo].[GDB_ITEMS] ADD CONSTRAINT [g1_ck] CHECK (([Shape].[STSrid]=(4326)))
GO
ALTER TABLE [dbo].[GDB_ITEMS] ADD CONSTRAINT [R6_pk] PRIMARY KEY CLUSTERED ([ObjectID]) WITH (FILLFACTOR=100, ALLOW_PAGE_LOCKS=OFF) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [Items_Name_idx] ON [dbo].[GDB_ITEMS] ([Name]) WITH (FILLFACTOR=100, ALLOW_PAGE_LOCKS=OFF) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [Items_PhysicalName_idx] ON [dbo].[GDB_ITEMS] ([PhysicalName]) WITH (FILLFACTOR=100, ALLOW_PAGE_LOCKS=OFF) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [Items_Type_idx] ON [dbo].[GDB_ITEMS] ([Type]) WITH (FILLFACTOR=100, ALLOW_PAGE_LOCKS=OFF) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [GDB_Items_UUID_idx] ON [dbo].[GDB_ITEMS] ([UUID]) WITH (FILLFACTOR=100, ALLOW_PAGE_LOCKS=OFF) ON [PRIMARY]
GO
CREATE SPATIAL INDEX [S1_idx] ON [dbo].[GDB_ITEMS] ([Shape]) USING geometry_auto_grid  WITH (BOUNDING_BOX = (-400, -90, 400, 90), CELLS_PER_OBJECT = 8, ALLOW_PAGE_LOCKS=OFF) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[GDB_ITEMS] TO [public] WITH GRANT OPTION
GO
GRANT INSERT ON  [dbo].[GDB_ITEMS] TO [public] WITH GRANT OPTION
GO
GRANT SELECT ON  [dbo].[GDB_ITEMS] TO [public] WITH GRANT OPTION
GO
GRANT UPDATE ON  [dbo].[GDB_ITEMS] TO [public] WITH GRANT OPTION
GO
ALTER TABLE [dbo].[GDB_ITEMS] SET ( LOCK_ESCALATION = DISABLE )
GO
