CREATE TABLE [dbo].[PROJECTROUTES]
(
[OBJECTID] [int] NOT NULL,
[projRteID] [int] NOT NULL,
[projDBS] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[projID] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[version] [smallint] NOT NULL,
[PhaseID] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[withEvents] [int] NOT NULL,
[Flag_area] [smallint] NOT NULL,
[Change_Type] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Inode] [int] NOT NULL,
[Jnode] [int] NOT NULL,
[dateLastUpdated] [datetime2] NULL,
[DateCreated] [datetime2] NULL,
[LastEditor] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[EditNotes] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Processing] [int] NULL,
[Enabled] [smallint] NULL,
[intProjID] [smallint] NULL,
[OnewayChange] [int] NULL,
[Oneway] [int] NULL,
[Shape] [sys].[geometry] NULL,
[GDB_GEOMATTR_DATA] [varbinary] (max) NULL,
[projRteID_1] [int] NULL,
[projDBS_1] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[projID_1] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[version_1] [int] NULL,
[InServiceDate] [smallint] NULL,
[OutServiceDate] [smallint] NULL,
[CompletionDate] [datetime2] NULL,
[Modes] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IJLanesGPAM] [int] NULL,
[IJLanesGPMD] [int] NULL,
[IJLanesGPPM] [int] NULL,
[IJLanesGPEV] [int] NULL,
[IJLanesGPNI] [int] NULL,
[JILanesGPAM] [int] NULL,
[JILanesGPMD] [int] NULL,
[JILanesGPPM] [int] NULL,
[JILanesGPEV] [int] NULL,
[JILanesGPNI] [int] NULL,
[IJlanesGPadjust] [numeric] (6, 2) NULL,
[JIlanesGPadjust] [numeric] (6, 2) NULL,
[IJLanesHOVAM] [int] NULL,
[IJLanesHOVMD] [int] NULL,
[IJLanesHOVPM] [int] NULL,
[IJLanesHOVEV] [int] NULL,
[IJLanesHOVNI] [int] NULL,
[JILanesHOVAM] [int] NULL,
[JILanesHOVMD] [int] NULL,
[JILanesHOVPM] [int] NULL,
[JILanesHOVEV] [int] NULL,
[JILanesHOVNI] [int] NULL,
[IJSpeedLimit] [int] NULL,
[JISpeedLimit] [int] NULL,
[IJVDFunc] [int] NULL,
[JIVDFunc] [int] NULL,
[IJLaneCapGP] [int] NULL,
[IJLaneCapHOV] [int] NULL,
[JILaneCapGP] [int] NULL,
[JILaneCapHOV] [int] NULL,
[IJSideWalks] [int] NULL,
[JISideWalks] [int] NULL,
[IJBikeLanes] [int] NULL,
[JIBikeLanes] [int] NULL,
[IJLanesTR] [int] NULL,
[JILanesTR] [int] NULL,
[IJLanesTK] [int] NULL,
[JILanesTK] [int] NULL,
[dateLastUpdated_1] [datetime2] NULL,
[DateCreated_1] [datetime2] NULL,
[LastEditor_1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EditNotes_1] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Processing_1] [int] NULL,
[IJBikeFacility] [int] NULL,
[JIBikeFacility] [int] NULL,
[IJBikeType] [int] NULL,
[JIBikeType] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PROJECTROUTES] ADD CONSTRAINT [g11_ck] CHECK (([SHAPE].[STSrid]=(2285)))
GO
ALTER TABLE [dbo].[PROJECTROUTES] ADD CONSTRAINT [R40_pk] PRIMARY KEY CLUSTERED ([OBJECTID]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [G112projRteID] ON [dbo].[PROJECTROUTES] ([projRteID]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
CREATE SPATIAL INDEX [S11_idx] ON [dbo].[PROJECTROUTES] ([Shape]) USING geometry_auto_grid  WITH (BOUNDING_BOX = (1143235.6470588236, -83079.705882353, 1555109, 483110), CELLS_PER_OBJECT = 16) ON [PRIMARY]
GO
