CREATE TABLE [dbo].[GDB_EDITINGTEMPLATES]
(
[objectid] [int] NOT NULL,
[globalid] [uniqueidentifier] NOT NULL,
[type] [smallint] NOT NULL,
[name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[defaulttool] [uniqueidentifier] NULL,
[datasetguid] [uniqueidentifier] NOT NULL,
[subtype] [int] NULL,
[definition] [varbinary] (max) NOT NULL,
[description] [nvarchar] (1024) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[thumbnail] [varbinary] (max) NULL,
[tags] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[visible] [smallint] NOT NULL,
[hash] [nvarchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[useridentity] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[status] [int] NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [EdTemplates_DTGuid_idx] ON [dbo].[GDB_EDITINGTEMPLATES] ([datasetguid]) WITH (FILLFACTOR=100, ALLOW_PAGE_LOCKS=OFF) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [EdTemplates_Globalid_idx] ON [dbo].[GDB_EDITINGTEMPLATES] ([globalid]) WITH (FILLFACTOR=100, ALLOW_PAGE_LOCKS=OFF) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [EdTemplates_Name_idx] ON [dbo].[GDB_EDITINGTEMPLATES] ([name]) WITH (FILLFACTOR=100, ALLOW_PAGE_LOCKS=OFF) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [EdTemplates_NameDT_idx] ON [dbo].[GDB_EDITINGTEMPLATES] ([name], [datasetguid]) WITH (FILLFACTOR=100, ALLOW_PAGE_LOCKS=OFF) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [R13_SDE_ROWID_UK] ON [dbo].[GDB_EDITINGTEMPLATES] ([objectid]) WITH (FILLFACTOR=100, ALLOW_PAGE_LOCKS=OFF) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [EdTemplates_Type_idx] ON [dbo].[GDB_EDITINGTEMPLATES] ([type]) WITH (FILLFACTOR=100, ALLOW_PAGE_LOCKS=OFF) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[GDB_EDITINGTEMPLATES] TO [public] WITH GRANT OPTION
GO
GRANT INSERT ON  [dbo].[GDB_EDITINGTEMPLATES] TO [public] WITH GRANT OPTION
GO
GRANT SELECT ON  [dbo].[GDB_EDITINGTEMPLATES] TO [public] WITH GRANT OPTION
GO
GRANT UPDATE ON  [dbo].[GDB_EDITINGTEMPLATES] TO [public] WITH GRANT OPTION
GO
ALTER TABLE [dbo].[GDB_EDITINGTEMPLATES] SET ( LOCK_ESCALATION = DISABLE )
GO
