CREATE TABLE [dbo].[D42]
(
[SDE_STATE_ID] [bigint] NOT NULL,
[SDE_DELETES_ROW_ID] [int] NOT NULL,
[DELETED_AT] [bigint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[D42] ADD CONSTRAINT [d42_pk] PRIMARY KEY CLUSTERED ([SDE_STATE_ID], [SDE_DELETES_ROW_ID], [DELETED_AT]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [d42_idx2] ON [dbo].[D42] ([DELETED_AT]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
