CREATE TABLE [dbo].[D50]
(
[SDE_STATE_ID] [bigint] NOT NULL,
[SDE_DELETES_ROW_ID] [int] NOT NULL,
[DELETED_AT] [bigint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[D50] ADD CONSTRAINT [d50_pk] PRIMARY KEY NONCLUSTERED ([SDE_STATE_ID], [SDE_DELETES_ROW_ID], [DELETED_AT]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
CREATE CLUSTERED INDEX [d50_idx2] ON [dbo].[D50] ([DELETED_AT]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
