CREATE TABLE [dbo].[SDE_version]
(
[MAJOR] [int] NOT NULL,
[MINOR] [int] NOT NULL,
[BUGFIX] [int] NOT NULL,
[DESCRIPTION] [nvarchar] (96) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RELEASE] [int] NOT NULL,
[SDESVR_REL_LOW] [int] NOT NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[TG_VERSION_HISTORY]   ON [dbo].[SDE_version] FOR INSERT, UPDATE AS 
  BEGIN 
  SET NOCOUNT ON 
    INSERT INTO dbo.SDE_version_history       (MAJOR,        MINOR,        BUGFIX,        DESCRIPTION,        RELEASE,        SDESVR_REL_LOW)     SELECT MAJOR, MINOR, BUGFIX, DESCRIPTION, RELEASE, SDESVR_REL_LOW        FROM INSERTED   END 
GO
ALTER TABLE [dbo].[SDE_version] ADD CONSTRAINT [version_pk] PRIMARY KEY CLUSTERED ([MAJOR]) WITH (FILLFACTOR=100, ALLOW_PAGE_LOCKS=OFF) ON [PRIMARY]
GO
GRANT SELECT ON  [dbo].[SDE_version] TO [public]
GO
ALTER TABLE [dbo].[SDE_version] SET ( LOCK_ESCALATION = DISABLE )
GO
