CREATE TABLE [dbo].[GDB_ITEMRELATIONSHIPS]
(
[ObjectID] [int] NOT NULL,
[UUID] [uniqueidentifier] NOT NULL,
[Type] [uniqueidentifier] NOT NULL,
[OriginID] [uniqueidentifier] NOT NULL,
[DestID] [uniqueidentifier] NOT NULL,
[Properties] [int] NULL,
[Attributes] [xml] NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[GDB_ITEMS_REL_TR] ON [dbo].[GDB_ITEMRELATIONSHIPS] 
FOR INSERT, UPDATE, DELETE AS 
BEGIN 
SET NOCOUNT ON 
SET LOCK_TIMEOUT 0 
SET XACT_ABORT OFF 
DECLARE @ErrorMessage NVARCHAR(2048), 
@ErrorSeverity INT, 
@ErrorState INT; 
IF (SELECT COUNT(*) from inserted WHERE Type NOT IN ('8DB31AF1-DF7C-4632-AA10-3CC44B0C6914', 'CC28387C-441F-4D7C-A802-41A160317FE0','79CC71C8-B7D9-4141-9014-B6373E236ABB', 'D022DE33-45BD-424C-88BF-5B1B6B957BD3')) > 0 OR 
(SELECT COUNT(*) from deleted WHERE Type NOT IN ('8DB31AF1-DF7C-4632-AA10-3CC44B0C6914', 'CC28387C-441F-4D7C-A802-41A160317FE0','79CC71C8-B7D9-4141-9014-B6373E236ABB', 'D022DE33-45BD-424C-88BF-5B1B6B957BD3')) > 0
BEGIN 
 BEGIN TRY 
UPDATE dbo.GDB_TABLES_LAST_MODIFIED SET last_modified_count = last_modified_count + 1 
WHERE table_name = 'GDB_ITEMRELATIONSHIPS' 
IF @@ROWCOUNT = 0 
BEGIN 
INSERT INTO dbo.GDB_TABLES_LAST_MODIFIED VALUES ('GDB_ITEMRELATIONSHIPS', 1) 
END 
END TRY 
BEGIN CATCH 
IF ERROR_NUMBER() != 1222 
BEGIN 
SELECT @ErrorMessage = ERROR_MESSAGE(), 
@ErrorSeverity = ERROR_SEVERITY(), 
@ErrorState = ERROR_STATE(); 
RAISERROR(@ErrorMessage, @ErrorSeverity, @ErrorState); 
END 
RETURN 
END CATCH 
END 
END
GO
ALTER TABLE [dbo].[GDB_ITEMRELATIONSHIPS] ADD CONSTRAINT [R7_pk] PRIMARY KEY CLUSTERED ([ObjectID]) WITH (FILLFACTOR=100, ALLOW_PAGE_LOCKS=OFF) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [GDB_ItemRel_DestID_idx] ON [dbo].[GDB_ITEMRELATIONSHIPS] ([DestID]) WITH (FILLFACTOR=100, ALLOW_PAGE_LOCKS=OFF) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [GDB_ItemRel_OriginID_idx] ON [dbo].[GDB_ITEMRELATIONSHIPS] ([OriginID]) WITH (FILLFACTOR=100, ALLOW_PAGE_LOCKS=OFF) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [GDB_ItemRel_Type_idx] ON [dbo].[GDB_ITEMRELATIONSHIPS] ([Type]) WITH (FILLFACTOR=100, ALLOW_PAGE_LOCKS=OFF) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [GDB_ItemRelationships_UUID_idx] ON [dbo].[GDB_ITEMRELATIONSHIPS] ([UUID]) WITH (FILLFACTOR=100, ALLOW_PAGE_LOCKS=OFF) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[GDB_ITEMRELATIONSHIPS] TO [public] WITH GRANT OPTION
GO
GRANT INSERT ON  [dbo].[GDB_ITEMRELATIONSHIPS] TO [public] WITH GRANT OPTION
GO
GRANT SELECT ON  [dbo].[GDB_ITEMRELATIONSHIPS] TO [public] WITH GRANT OPTION
GO
GRANT UPDATE ON  [dbo].[GDB_ITEMRELATIONSHIPS] TO [public] WITH GRANT OPTION
GO
ALTER TABLE [dbo].[GDB_ITEMRELATIONSHIPS] SET ( LOCK_ESCALATION = DISABLE )
GO
