CREATE TABLE [dbo].[D35]
(
[SDE_STATE_ID] [bigint] NOT NULL,
[SDE_DELETES_ROW_ID] [int] NOT NULL,
[DELETED_AT] [bigint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[D35] ADD CONSTRAINT [d35_pk] PRIMARY KEY CLUSTERED ([SDE_STATE_ID], [SDE_DELETES_ROW_ID], [DELETED_AT]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [d35_idx2] ON [dbo].[D35] ([DELETED_AT]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
