CREATE TABLE [dbo].[a21]
(
[OBJECTID] [int] NOT NULL,
[PSRCEdgeID] [int] NULL,
[IJLanesGPAM] [int] NOT NULL,
[IJLanesGPMD] [int] NOT NULL,
[IJLanesGPPM] [int] NOT NULL,
[IJLanesGPEV] [int] NOT NULL,
[IJLanesGPNI] [int] NOT NULL,
[JILanesGPAM] [int] NOT NULL,
[JILanesGPMD] [int] NOT NULL,
[JILanesGPPM] [int] NOT NULL,
[JILanesGPEV] [int] NOT NULL,
[JILanesGPNI] [int] NOT NULL,
[IJlanesGPadjust] [numeric] (6, 2) NOT NULL,
[JIlanesGPadjust] [numeric] (6, 2) NOT NULL,
[IJLanesHOVAM] [int] NOT NULL,
[IJLanesHOVMD] [int] NOT NULL,
[IJLanesHOVPM] [int] NOT NULL,
[IJLanesHOVEV] [int] NOT NULL,
[IJLanesHOVNI] [int] NOT NULL,
[JILanesHOVAM] [int] NOT NULL,
[JILanesHOVMD] [int] NOT NULL,
[JILanesHOVPM] [int] NOT NULL,
[JILanesHOVEV] [int] NOT NULL,
[JILanesHOVNI] [int] NOT NULL,
[IJSpeedLimit] [int] NOT NULL,
[JISpeedLimit] [int] NOT NULL,
[IJVDFunc] [int] NOT NULL,
[JIVDFunc] [int] NOT NULL,
[IJLaneCapGP] [int] NOT NULL,
[IJLaneCapHOV] [int] NOT NULL,
[JILaneCapGP] [int] NOT NULL,
[JILaneCapHOV] [int] NOT NULL,
[IJSideWalks] [int] NOT NULL,
[JISideWalks] [int] NOT NULL,
[IJBikeLanes] [int] NOT NULL,
[JIBikeLanes] [int] NOT NULL,
[IJLanesTR] [int] NOT NULL,
[JILanesTR] [int] NOT NULL,
[IJLanesTK] [int] NOT NULL,
[JILanesTK] [int] NOT NULL,
[PSRCE2_ID] [int] NULL,
[dateLastUpdated] [datetime2] NULL,
[DateCreated] [datetime2] NULL,
[LastEditor] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DataSource] [smallint] NOT NULL,
[Processing] [int] NULL,
[BikeSigns] [int] NULL,
[SidewalkSource] [smallint] NULL,
[BikeEditorNotes] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IJBikeFacility] [int] NULL,
[JIBikeFacility] [int] NULL,
[IJPedFacilities] [int] NULL,
[JIPedFacilities] [int] NULL,
[IJBikeType] [int] NULL,
[JIBikeType] [int] NULL,
[IJBikeFacilities] [int] NULL,
[JIBikeFacilities] [int] NULL,
[IJCorridorID] [int] NULL,
[JICorridorID] [int] NULL,
[Channelization] [numeric] (38, 8) NULL,
[BikeSource_hold] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BikeSource] [smallint] NULL,
[PedBikeNotes] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SDE_STATE_ID] [bigint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[a21] ADD CONSTRAINT [a21_rowid_ix1] PRIMARY KEY NONCLUSTERED ([OBJECTID], [SDE_STATE_ID]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [a21_state_ix2] ON [dbo].[a21] ([SDE_STATE_ID]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
