CREATE TABLE [dbo].[EVTNAMEDROUTES]
(
[OBJECTID] [int] NOT NULL,
[NRouteID] [int] NULL,
[MStart] [numeric] (8, 2) NOT NULL,
[MStop] [numeric] (8, 2) NOT NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [G96NRouteID] ON [dbo].[EVTNAMEDROUTES] ([NRouteID]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [R26_SDE_ROWID_UK] ON [dbo].[EVTNAMEDROUTES] ([OBJECTID]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
