CREATE TABLE [dbo].[a47]
(
[OBJECTID] [int] NOT NULL,
[EdgeID] [int] NOT NULL,
[PSRC_EdgeID] [int] NOT NULL,
[Scenario_ID] [int] NULL,
[Scen_Link_ID] [int] NOT NULL,
[Inode] [int] NOT NULL,
[Jnode] [int] NOT NULL,
[Enabled] [smallint] NULL,
[Shape] [sys].[geometry] NULL,
[GDB_GEOMATTR_DATA] [varbinary] (max) NULL,
[SDE_STATE_ID] [bigint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[a47] ADD CONSTRAINT [A_g18_ck] CHECK (([SHAPE].[STSrid]=(2285)))
GO
ALTER TABLE [dbo].[a47] ADD CONSTRAINT [a47_rowid_ix1] PRIMARY KEY CLUSTERED ([OBJECTID], [SDE_STATE_ID]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [a47_state_ix2] ON [dbo].[a47] ([SDE_STATE_ID]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
CREATE SPATIAL INDEX [SA18_idx] ON [dbo].[a47] ([Shape]) USING geometry_auto_grid  WITH (BOUNDING_BOX = (1272835.1764705882, 175613.29411764711, 1277298, 175956.5882352941), CELLS_PER_OBJECT = 8) ON [PRIMARY]
GO
