CREATE TABLE [dbo].[NAMEDROUTES]
(
[OBJECTID] [int] NOT NULL,
[NRouteID] [int] NOT NULL,
[Route_Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Processing] [int] NOT NULL,
[dateLastUpdated] [datetime2] NULL,
[Enabled] [smallint] NULL,
[Shape] [sys].[geometry] NULL,
[GDB_GEOMATTR_DATA] [varbinary] (max) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NAMEDROUTES] ADD CONSTRAINT [g5_ck] CHECK (([SHAPE].[STSrid]=(2285)))
GO
ALTER TABLE [dbo].[NAMEDROUTES] ADD CONSTRAINT [R34_pk] PRIMARY KEY CLUSTERED ([OBJECTID]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [G106NRouteID] ON [dbo].[NAMEDROUTES] ([NRouteID]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
CREATE SPATIAL INDEX [S5_idx] ON [dbo].[NAMEDROUTES] ([Shape]) USING geometry_auto_grid  WITH (BOUNDING_BOX = (1214035.2352941176, 36301.1764705883, 1246784.1764705882, 40303.8235294117), CELLS_PER_OBJECT = 16) ON [PRIMARY]
GO
