CREATE TABLE [dbo].[GDB_REPLICALOG]
(
[ID] [int] NOT NULL,
[ReplicaID] [int] NOT NULL,
[Event] [int] NOT NULL,
[ErrorCode] [int] NOT NULL,
[LogDate] [datetime2] NOT NULL,
[SourceBeginGen] [int] NOT NULL,
[SourceEndGen] [int] NOT NULL,
[TargetGen] [int] NOT NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[GDB_REP_LOG_TR] ON [dbo].[GDB_REPLICALOG] 
FOR INSERT, UPDATE, DELETE AS 
BEGIN 
SET NOCOUNT ON 
SET LOCK_TIMEOUT 0 
SET XACT_ABORT OFF 
DECLARE @ErrorMessage NVARCHAR(2048), 
@ErrorSeverity INT, 
@ErrorState INT; 
 BEGIN TRY 
UPDATE dbo.GDB_TABLES_LAST_MODIFIED SET last_modified_count = last_modified_count + 1 
WHERE table_name = 'GDB_REPLICALOG' 
IF @@ROWCOUNT = 0 
BEGIN 
INSERT INTO dbo.GDB_TABLES_LAST_MODIFIED VALUES ('GDB_REPLICALOG', 1) 
END 
END TRY 
BEGIN CATCH 
IF ERROR_NUMBER() != 1222 
BEGIN 
SELECT @ErrorMessage = ERROR_MESSAGE(), 
@ErrorSeverity = ERROR_SEVERITY(), 
@ErrorState = ERROR_STATE(); 
RAISERROR(@ErrorMessage, @ErrorSeverity, @ErrorState); 
END 
RETURN 
END CATCH 
END 

GO
CREATE UNIQUE CLUSTERED INDEX [R10_SDE_ROWID_UK] ON [dbo].[GDB_REPLICALOG] ([ID]) WITH (ALLOW_PAGE_LOCKS=OFF) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[GDB_REPLICALOG] TO [public] WITH GRANT OPTION
GO
GRANT INSERT ON  [dbo].[GDB_REPLICALOG] TO [public] WITH GRANT OPTION
GO
GRANT SELECT ON  [dbo].[GDB_REPLICALOG] TO [public] WITH GRANT OPTION
GO
GRANT UPDATE ON  [dbo].[GDB_REPLICALOG] TO [public] WITH GRANT OPTION
GO
ALTER TABLE [dbo].[GDB_REPLICALOG] SET ( LOCK_ESCALATION = DISABLE )
GO
