CREATE TABLE [dbo].[EVTLINEPROJECTOUTCOMES]
(
[OBJECTID] [int] NOT NULL,
[projRteID] [int] NULL,
[projDBS] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ProjID_Ver] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[projID] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[version] [smallint] NOT NULL,
[MStart] [numeric] (9, 2) NOT NULL,
[MStop] [numeric] (9, 2) NOT NULL,
[PhaseID] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InServiceDate] [smallint] NOT NULL,
[OutServiceDate] [smallint] NOT NULL,
[CompletionDate] [datetime2] NOT NULL,
[newFacilityType] [smallint] NOT NULL,
[Modes] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Length] [numeric] (9, 2) NOT NULL,
[IJLanesGPAM] [int] NOT NULL,
[IJLanesGPMD] [int] NOT NULL,
[IJLanesGPPM] [int] NOT NULL,
[IJLanesGPEV] [int] NOT NULL,
[IJLanesGPNI] [int] NOT NULL,
[JILanesGPAM] [int] NOT NULL,
[JILanesGPMD] [int] NOT NULL,
[JILanesGPPM] [int] NOT NULL,
[JILanesGPEV] [int] NOT NULL,
[JILanesGPNI] [int] NOT NULL,
[IJLanesHOVAM] [int] NOT NULL,
[IJLanesHOVMD] [int] NOT NULL,
[IJLanesHOVPM] [int] NOT NULL,
[IJLanesHOVEV] [int] NOT NULL,
[IJLanesHOVNI] [int] NOT NULL,
[JILanesHOVAM] [int] NOT NULL,
[JILanesHOVMD] [int] NOT NULL,
[JILanesHOVPM] [int] NOT NULL,
[JILanesHOVEV] [int] NOT NULL,
[JILanesHOVNI] [int] NOT NULL,
[IJSpeedLimit] [int] NOT NULL,
[JISpeedLimit] [int] NOT NULL,
[IJFFS] [numeric] (7, 4) NOT NULL,
[JIFFS] [numeric] (7, 4) NOT NULL,
[IJVDFunc] [int] NOT NULL,
[JIVDFunc] [int] NOT NULL,
[IJLaneCapGP] [int] NOT NULL,
[IJLaneCapHOV] [int] NOT NULL,
[JILaneCapGP] [int] NOT NULL,
[JILaneCapHOV] [int] NOT NULL,
[IJSideWalks] [int] NOT NULL,
[JISideWalks] [int] NOT NULL,
[IJBikeLanes] [int] NOT NULL,
[JIBikeLanes] [int] NOT NULL,
[IJLanesTR] [int] NOT NULL,
[JILanesTR] [int] NOT NULL,
[IJLanesTK] [int] NOT NULL,
[JILanesTK] [int] NOT NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [R19_SDE_ROWID_UK] ON [dbo].[EVTLINEPROJECTOUTCOMES] ([OBJECTID]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [G89projRteID] ON [dbo].[EVTLINEPROJECTOUTCOMES] ([projRteID]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
