CREATE TABLE [dbo].[EMME2EDGES]
(
[OBJECTID] [int] NOT NULL,
[EdgeID] [int] NOT NULL,
[PSRC_EdgeID] [int] NOT NULL,
[Scenario_ID] [int] NULL,
[Scen_Link_ID] [int] NOT NULL,
[Inode] [int] NOT NULL,
[Jnode] [int] NOT NULL,
[Enabled] [smallint] NULL,
[Shape] [sys].[geometry] NULL,
[GDB_GEOMATTR_DATA] [varbinary] (max) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EMME2EDGES] ADD CONSTRAINT [g18_ck] CHECK (([SHAPE].[STSrid]=(2285)))
GO
ALTER TABLE [dbo].[EMME2EDGES] ADD CONSTRAINT [R47_pk] PRIMARY KEY CLUSTERED ([OBJECTID]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
CREATE SPATIAL INDEX [S18_idx] ON [dbo].[EMME2EDGES] ([Shape]) USING geometry_auto_grid  WITH (BOUNDING_BOX = (1272835.1764705882, 175613.29411764711, 1277298, 175956.5882352941), CELLS_PER_OBJECT = 16) ON [PRIMARY]
GO
