CREATE TABLE [dbo].[T_1_DIRTYAREAS]
(
[ObjectID] [int] NOT NULL,
[IsRetired] [int] NOT NULL,
[DirtyArea] [sys].[geometry] NULL,
[GDB_GEOMATTR_DATA] [varbinary] (max) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[T_1_DIRTYAREAS] ADD CONSTRAINT [g20_ck] CHECK (([DirtyArea].[STSrid]=(2285)))
GO
ALTER TABLE [dbo].[T_1_DIRTYAREAS] ADD CONSTRAINT [R49_pk] PRIMARY KEY CLUSTERED ([ObjectID]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [GDB_122_IsRetire] ON [dbo].[T_1_DIRTYAREAS] ([IsRetired]) WITH (FILLFACTOR=100) ON [PRIMARY]
GO
CREATE SPATIAL INDEX [S20_idx] ON [dbo].[T_1_DIRTYAREAS] ([DirtyArea]) USING geometry_auto_grid  WITH (BOUNDING_BOX = (-117104300, -99539600, 120385100, 101712900), CELLS_PER_OBJECT = 16) ON [PRIMARY]
GO
